GoogleCloudPlatform/functions-framework-ruby

lib/functions_framework/server.rb, test/test_server.rb
The server should return a 404 when receiving a request for `/favicon.ico` or `/robots.txt` according to a recent update to the spec.
=> fix: return 404 on favicon and robots paths

README.md, bin/functions-framework-ruby, examples/echo/.toys.rb, examples/echo/Dockerfile, functions_framework.gemspec, lib/functions_framework.rb, lib/functions_framework/cli.rb
After the discussion in #9, I think we should provide an unambiguous `functions-framework-ruby` executable (as well as the current `functions-framework`). So that we have it, in case the issue does turn out to be more serious. This PR retains the current `functions-framework` executable but also provides the same executable under the `functions-framework-ruby` name, _and_ documents that as the preferred executable name.
=> feat: Add functions-framework-ruby executable

lib/functions_framework/testing.rb, test/function_definitions/simple_event.rb, test/function_definitions/simple_http.rb, test/test_testing.rb
Previously, `FunctionsFramework::Testing.load_temporary` would reload all the function definitions each time it is called, even if called with the same file. This could cause redefinition warnings or errors if the file defined non-function things like methods, classes, or constants. Now, we cache the definitions and just apply the cache if the same file is loaded using load_temporary. This probably also gives us a performance benefit in large tests.
Also implement more test cases for the test framework.
=> fix: Cache definitions loaded using Testing.load_temporary

lib/functions_framework.rb, lib/functions_framework/cli.rb, test/test_cli.rb
This _allows_ the `--signature-type` flag to be passed to Ruby's functions framework executable. Technically, this is not needed because Ruby's function definition syntax makes the signature type explicit. However, I wasn't clear from my reading of the [FF spec](https://github.com/GoogleCloudPlatform/functions-framework) whether:
* the framework _must_ accept a `--signature-type` flag (even if it is not strictly necessary)?
* any signature type provided (either by `--signature-type` flag, or `FUNCTION_SIGNATURE_TYPE` environment variable), _must_ be respected?
@grant ^
If it turns out that either of the above is true, then this PR provides an implementation for Ruby. It _optionally_ accepts both input options (the environment variable and command-line flag), and if a signature type is …
=> feat: Accept --signature-type on the command line

lib/functions_framework/server.rb
These are internal, undocumented names and should not have any effect on the public interface.
=> refactor: change some internal names for inclusivity

examples/echo/README.md, examples/echo/app.rb, examples/echo/test/test_app.rb
The sample functions were named `http-sample` and `event-sample` but hyphens are not allowed by GCF. Changed to underscores.
=> fix: Rename echo sample functions to conform to GCF restrictions

lib/functions_framework/legacy_event_converter.rb, test/test_legacy_event_converter.rb
@jskeet identified a difference in how PubSub event data is presented in Cloud Run. It was decided that functions frameworks would adjust their legacy event to CloudEvent conversion logic to match.
=> fix: Update pubsub CloudEvent data conversion to match Cloud Run

README.md, docs/overview.md
Change the command line to test the start the sample with curl to use http instead of https as that's what the framework accepts.
=> docs: Change curl to use http instead of https

lib/functions_framework/function.rb, test/function_definitions/return_http.rb, test/function_definitions/simple_event.rb, test/test_cli.rb, test/test_function.rb, test/test_registry.rb, test/test_testing.rb
Functions raised `LocalJumpError` if they executed an explicit `return` statement directly in the function block. Fixed by setting the lambda bit on all functions, by recasting them as methods on an anonymous class.
(This also opens the door for future use of that anonymous class as a "context" from which we could potentially get things like per-invocation loggers, the source and target of the running function, etc. Such extensions aren't implemented now, pending design discussion, but they are now possible.)
Also updated test cases to use function names without hyphens.
=> fix: Allow return statements in functions

docs/writing-functions.md, lib/functions_framework/cloud_events.rb, lib/functions_framework/cloud_events/errors.rb, lib/functions_framework/cloud_events/event.rb, lib/functions_framework/cloud_events/event/field_interpreter.rb, lib/functions_framework/cloud_events/event/v0.rb, lib/functions_framework/cloud_events/http_binding.rb, lib/functions_framework/cloud_events/json_format.rb, test/cloud_events/test_event.rb, test/cloud_events/test_event_v0.rb, test/cloud_events/test_json_format.rb, test/test_legacy_event_converter.rb
Updates the embedded CloudEvents classes to add support for CloudEvents 0.3, in preparation for potential extraction to the official SDK.
Additionally:
* The `CloudEventsError` class properly subclasess `StandardError` instead of `RuntimeError`.
* Removed redundant `_string` accessors from the event class, since the raw forms are already available via `[]`.
* A variety of corrections to the docs for event-related classes.
=> feat: Support CloudEvents 0.3

lib/functions_framework.rb, lib/functions_framework/execution_context.rb, lib/functions_framework/function.rb, lib/functions_framework/registry.rb, lib/functions_framework/server.rb, lib/functions_framework/testing.rb, test/test_function.rb, test/test_registry.rb
* The `self` during a function invocation is currently an anonymous class. Provide a base class for that anonymous class (which gives us a place to include some context-related accessors such as the logger.)
* Drop the legacy `:event` function type, which was deprecated and only marginally supported anyway. Now only `:http` and `:cloud_event` types are supported.
=> feat: Provide an explicit execution context class

lib/functions_framework/cloud_events/http_binding.rb, test/cloud_events/test_http_binding.rb
I finally think I understand the whole percent-encoding part of the CE spec...
=> fix: Do correct percent-encoding of CloudEvents binary headers

docs/deploying-functions.md
Text for main addition taken from Cloud Functions section, rewording to mention it's the Dockerfile enforcing this (through the `bundle config --local frozen true` command)
Also minor filename spelling.
=> Docs update: ensure Gemfile.lock for Cloud Run, minor spelling

README.md, docs/overview.md, docs/testing-functions.md, docs/writing-functions.md, functions_framework.gemspec, lib/functions_framework.rb, lib/functions_framework/function.rb, lib/functions_framework/registry.rb
Use github pages hosted reference docs instead of rubydoc.info hosted pages.
=> docs: Update links to reference documentation

lib/functions_framework.rb
Currently the logger uses `::STDERR` as it's log device. This poses a problem when you'd like to capture or suppress those logs (typically when testing).
By using `$stderr` instead (which by default is set to equal `::STDERR`), we'd be able to dynamically change the device if/when desired.
Update the log device to be `$stderr` allowing functions like the following to be used to silence output in tests.
```ruby
def capture_io
$stdout = StringIO.new
$stderr = StringIO.new
yield
ensure
$stdout = ::STDOUT
$stderr = ::STDERR
end
```
=> Use global $stderr rather than STDERR for logger

README.md, docs/deploying-functions.md, docs/overview.md, docs/writing-functions.md, functions_framework.gemspec
* The deployment docs incorrectly said that you could specify the file that defines the function when deploying to Cloud Functions. This is not true for Ruby, and the docs have been fixed.
* The release status for Ruby on Cloud Functions was incorrectly described as "preview", but should be "alpha". Fixed.
* Updated the gem's long description to be a bit more detailed.
=> docs: Fix instructions for deployment to Google Cloud Functions

CHANGELOG.md, lib/functions_framework/version.rb
*  **functions_framework** version 0.5.1 -> **0.5.2**
----
* FIXED: Use global $stderr rather than STDERR for logger 
* DOCS: Fix instructions for deployment to Google Cloud Functions
=> release: Release functions_framework 0.5.2

bin/functions-framework, bin/functions-framework-ruby, docs/writing-functions.md, lib/functions_framework.rb, lib/functions_framework/cli.rb, lib/functions_framework/registry.rb, lib/functions_framework/server.rb, test/function_definitions/startup_block.rb, test/test_cli.rb, test/test_registry.rb
Important: rebase when merging, rather than squash, so the three conventional commit messages get into the history.
This implements a verification function that will be used by the GCF build process to determine that the Ruby code is syntactically well-formed and actually defines the function it wants to use. It comprises three commits that will show up in the changelog:
* **feat: You can use the --version flag to print the framework version**
* Implements a `--version` flag that prints the framework version. This will be used by the GCF buildpack to validate minimum framework version.
* Refactor of the CLI run process so that `--help` and `--version` print their output during `run` rather than `parse_args`. This makes it possible to test those flags since they don't have to …
=> feat: Implement verification function (3 commits)

CHANGELOG.md, lib/functions_framework/version.rb
*  **functions_framework 0.6.0** (was 0.5.2)
----
* ADDED: You can use the --version flag to print the framework version
* ADDED: You can use the --verify flag to verify that a given function is defined
* ADDED: You can now define blocks that are executed at server startup
=> release: Release functions_framework 0.6.0

.github/workflows/unit.yml, .rubocop.yml, README.md, docs/overview.md, docs/testing-functions.md, docs/writing-functions.md, functions_framework.gemspec, lib/functions_framework.rb, lib/functions_framework/function.rb, lib/functions_framework/registry.rb, lib/functions_framework/server.rb, lib/functions_framework/testing.rb, test/function_definitions/simple_event.rb, test/function_definitions/simple_http.rb, test/function_definitions/startup_block.rb, test/test_cli.rb, test/test_function.rb, test/test_main.rb, test/test_registry.rb, test/test_server.rb, test/test_testing.rb
A set of changes toward better support for shared resources such as remote service clients, after working on writing samples against the initial interfaces. Specifically:
* Now requires Ruby 2.5 or later.
* Renamed "context" hash to "globals" and made it read-only for normal functions.
* Startup blocks are no longer passed the server config.
* Provided a "logger" convenience method in the context object.
* Globals can be set from startup blocks, which is useful for initializing shared resources.
* Support for testing startup tasks in the Testing module.
* Support for controlling logging in the Testing module.
* Fixed crash introduced in 0.6 when a block didn't declare an expected argument.
* Better support for running concurrent tests.
* Expanded documentation on initialization, execution …
=> feat!: Rework globals mechanism to better support shared resources

.github/workflows/release-hook-on-open.yml, .github/workflows/unit.yml, .toys/release/.data/templates/release-hook-on-open.yml.erb, .toys/release/.lib/release_utils.rb
This patch fixes the conventional commit linter action. Previously, when a PR was opened from a fork and the commit message failed linting, the checker could not post details of the problem in a PR comment as intended, because the action's token didn't have sufficient permissions. Now we use a different trigger that runs in the base repo's context, thus giving the token enough permissions to write to the PR.
=> chore: Fix reporting of conventional commit lint issues

CHANGELOG.md, lib/functions_framework/version.rb
*  **functions_framework 0.7.1** (was 0.7.0)
----
* DOCS: Fix several errors in the writing-functions doc samples
* DOCS: Update README.md 
* DOCS: Updated documentation to note public release of GCF support
=> release: Release functions_framework 0.7.1

CHANGELOG.md, lib/functions_framework/version.rb
*  **functions_framework 0.8.0** (was 0.7.1)
----
* ADDED: Support for lazily-initialized globals
=> release: Release functions_framework 0.8.0

.github/workflows/conformance.yml, lib/functions_framework/legacy_event_converter.rb, test/test_legacy_event_converter.rb
Also enable legacy to CloudEvent mapping validation in conformance test config.
=> fix: Conformance fixes for Firebase to CloudEvent conversions

CHANGELOG.md, README.md, docs/overview.md, docs/writing-functions.md, lib/functions_framework/version.rb
*  **functions_framework 0.9.0** (was 0.8.0)
----
* BREAKING CHANGE: Servers are configured as single-threaded in production by default
* FIXED: Conformance fixes for Firebase to CloudEvent conversions 
* FIXED: Set correct CloudEvent subject when converting a Firebase Auth event
* FIXED: Fixed an error when setting a global …
=> release: Release functions_framework 0.9.0

.github/workflows/conformance.yml, lib/functions_framework/server.rb, lib/functions_framework/testing.rb, test/test_server.rb
=> fix: Set the charset when autogenerating a content-type for a response

functions_framework.gemspec, lib/functions_framework/legacy_event_converter.rb, test/legacy_events_data/pubsub_utf8.json, test/test_legacy_event_converter.rb
=> fix: Properly handle conversion of non-ascii characters in legacy event strings

lib/functions_framework/legacy_event_converter.rb, test/legacy_events_data/raw_pubsub.json, test/test_legacy_event_converter.rb
=> feat: Support raw pubsub events sent by the pubsub emulator

CHANGELOG.md, lib/functions_framework/version.rb
*  **functions_framework 0.10.0** (was 0.9.0)
----
* ADDED: Support raw pubsub events sent by the pubsub emulator 
* FIXED: Set proper response content-type charset 
* FIXED: Properly handle conversion of non-ascii characters in legacy event strings 
* FIXED: Properly handle conversion of non-ascii characters in legacy event …
=> release: Release functions_framework 0.10.0

.github/workflows/conformance.yml, lib/functions_framework/legacy_event_converter.rb, test/test_legacy_event_converter.rb
This commit updates the CloudEvent conversion for Pubsub events to add the `messageId` and `publishedTime` from the legacy event context in order to better form to the [PubSub CloudEvent schema](https://github.com/googleapis/google-cloudevents/blob/master/proto/google/events/cloud/pubsub/v1/data.proto)
=> update the pubsub ce event conversion logic to better align to Eventarc

.github/workflows/conformance.yml, lib/functions_framework/legacy_event_converter.rb, test/legacy_events_data/firebase-db1.json, test/legacy_events_data/firebase-dbdelete1.json, test/legacy_events_data/firebase-dbdelete2.json, test/test_legacy_event_converter.rb
Recently the format of Firebase RTDB cloudevent was updated to include location information in the source. When upcasting, this can be derived from the domain field of a legacy event as described [here](https://github.com/GoogleCloudPlatform/functions-framework-conformance/blob/master/docs/mapping.md#firebase-rtdb-events-tentative).
This commit also updates the Functions Framework Conformance Github action to a version that tests this logic.
=> Update firebasedatabase event conversion logic

CHANGELOG.md, lib/functions_framework/version.rb
*  **functions_framework 0.11.0** (was 0.10.0)
----
* FIXED: Updated the Pub/Sub event conversion logic to better align to Eventarc 
* FIXED: Update CloudEvents dependency 
* FIXED: Loosen firebasedatabase domain restriction in legacy event conversion
=> release: Release functions_framework 0.11.0

CHANGELOG.md, README.md, docs/overview.md, docs/writing-functions.md, lib/functions_framework/version.rb
*  **functions_framework 1.0.0** (was 0.11.0)
----
* (No significant changes)
=> release: Release functions_framework 1.0.0

.github/workflows/conformance.yml, functions_framework.gemspec, lib/functions_framework/legacy_event_converter.rb, test/test_legacy_event_converter.rb
See https://github.com/GoogleCloudPlatform/functions-framework-conformance/pull/79
=> fix: Update legacy event conversion to set the correct types for firebase database events

lib/functions_framework/server.rb, lib/functions_framework/testing.rb, test/test_server.rb
An error's backtrace is an array, and the formatter isn't taking that into consideration. Here's what an error currently looks like:
```
E, [2021-11-29T00:31:23.035715 #41693] ERROR -- : RuntimeError: Boom
["/path/to/app.rb:12:in `block in <top (required)>'", "/path/to/functions_framework-1.0.1/lib/functions_framework/function.rb:164:in `call'", "/path/to/functions_framework-1.0.1/lib/functions_framework/server.rb:407:in `call'", "/path/to/puma-5.5.2/lib/puma/request.rb:77:in `block in handle_request'", "/path/to/puma-5.5.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'", "/path/to/puma-5.5.2/lib/puma/request.rb:76:in `handle_request'", "/path/to/puma-5.5.2/lib/puma/server.rb:447:in `process_client'", "/path/to/puma-5.5.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'"]
``` …
=> Format the error backtrace

lib/functions_framework/server.rb
This will allow some concurrency on deployment options that support it.
The value of 8 is chosen based on Ruby best practices to provide enough concurrency to prevent IO-bound requests from blocking too much, while keeping GVL contention down. MRI is not designed for massive parallelism.
In the future, we can also consider supporting worker forking. We do not do so right now to keep memory use stable.
=> feat: Increase default max thread pool size to 8

lib/functions_framework/server.rb
=> fix: Flush stdout and stderr streams at the end of each request

.kokoro/release.sh, CHANGELOG.md, lib/functions_framework/version.rb
Also reverts the 1.1.0 release commit so we can try again with the new release-please tagger.
=> chore: Disable cloud-rad build for now

.github/release-please.yml, .github/release-trigger.yml
https://github.com/googleapis/repo-automation-bots/tree/main/packages/release-trigger will handle triggering the actual release job (uses same logic internally)
=> build: switch to release-please tagging

.github/workflows/buildpack-integration-test.yml, test/conformance/.gitignore, test/conformance/prerun.sh
See [functions-framework-conformance builidpack integration workflow PR](https://github.com/GoogleCloudPlatform/functions-framework-conformance/pull/99) for more information.
=> chore: add GCF buildpack integration test Workflow

.github/workflows/conformance.yml, .github/workflows/lint.yml, .github/workflows/push-gh-pages.yml, .github/workflows/unit.yml, .rubocop.yml
1. ruby/setup-ruby - use `bundler-cache: true`, remove `bundle install` from other steps
2. actions/checkout@v2 -> actions/checkout@v3
3. actions/setup-go@v2 -> actions/setup-go@v3
=> chore: CI - unit.yml - move bundle install into ruby/setup-ruby, use PS in Windows

.github/CONTRIBUTING.md, .github/workflows/conformance.yml, .github/workflows/unit.yml, Gemfile, README.md, docs/deploying-functions.md, docs/overview.md, functions_framework.gemspec, lib/functions_framework/cli.rb, lib/functions_framework/server.rb, test/test_server.rb
Also made minor style adjustments for newer versions of Rubocop.
=> feat: Update minimum Ruby version to 2.6

.github/workflows/conformance.yml, .github/workflows/unit.yml
Ruby 3.2 goes Public Preview for GCF and GAE next week (starting 02/27).
=> chore: Add Ruby 3.2 to the CI matrix.

.toys/ci.rb, Gemfile, functions_framework.gemspec, lib/functions_framework/server.rb, lib/functions_framework/testing.rb, test/test_server.rb
Handles breaking changes in Puma 6 ad Rack 3, and introduces tests against the Puma and Rack support matrix (Puma 4, 5, 6 x Rack 2, 3)
Supersedes #146
=> fix: Support puma 6 and rack 3

.github/workflows/buildpack-integration-test.yml, test/conformance/prerun.sh
Update buildpack test workflow to use the latest version of functions-framework-conformance which includes fixes to use the latest versions of the Google Cloud buildpacks.
=> chore: fix buildpack integration tests

.github/workflows/conformance.yml, lib/functions_framework/cli.rb, test/conformance/app.rb
Validation in lib/functions_framework/cli.rb prevents `typed` functions from working with the `http` signature type which is set in production. This change enables the `typed` signature to be used on GCP.
=> fix: enable typed function compatibility with http signature

.rubocop.yml, lib/functions_framework/server.rb
The `Style/RedundantCondition` cop seems to be flagging this case now. I would argue it's a false positive, but I'm not confident that viewpoint will be popular enough to force rubocop to revert its behavior. Unfortunately there doesn't seem to be a good alternative for this functionality that isn't also flagged by rubocop. I've made the judgment call that reverting to the "double-negative" idiom is probably the best option that preserves the intent while minimizing the blast radius of disabling a rubocop check. This of course has no functional impact on the code; hence I'm classifying it as "chore:" for conventional commit purposes.
=> chore: Work around an annoying rubocop change
